### ISSUE TITLE
Fahrenheit shown in log

### ISSUE THREAD

**Issue by sainio** [BobAtchley/weewx-ws6in1#10]
I have set my unit to use metric and also metric is selected for weewx, but running the plugin shows fahrenheit and mHg values in the log:
LOOP:   2021-03-30 19:42:05 EEST (1617122525) altimeter: 29.938877113381416, appTemp: 41.29427880774203, barometer: 29.9138773375, cloudbase: 713.9114445731618, dateTime: 1617122525, dayRain: 0.04, dewpoint: 40.82, extraHumid1: None, extraHumid2: None, extraHumid3: None, extraHumid4: None, extraHumid5: None, extraHumid6: None, extraHumid7: None, extraTemp1: None, extraTemp2: None, extraTemp3: None, extraTemp4: None, extraTemp5: None, extraTemp6: None, extraTemp7: None, heatindex: 41.651, humidex: 43.34, inDewpoint: 43.79440779562091, inHumidity: 30, inTemp: 77.72, maxSolarRad: None, outHumidity: 91, outTemp: 43.34, pressure: 29.766227400000002**, rain: 0.0, rainRate: 0.0, usUnits: 1, UV: 0, windchill: 43.34, windDir: None, windGust: 0.0, windSpeed: 0.0

Is this a bug?

**Comment by BobAtchley** [comment]
This is ... odd.  I also have set my unit and weewx to metric and I get:
LOOP:   2021-03-30 16:49:03 UTC (1617122943) altimeter: 1026.7690111510901, appTemp: 20.206407870902225, barometer: 1026, cloudbase: 2507.4462520250972, dateTime: 1617122943, dayRain: 0.0, dewpoint: 2.3, extraHumid1: None, extraHumid2: 30, extraHumid3: None, extraHumid4: None, extraHumid5: None, extraHumid6: None, extraHumid7: None, extraTemp1: 22.3, extraTemp2: 21.3, extraTemp3: None, extraTemp4: None, extraTemp5: None, extraTemp6: None, extraTemp7: None, heatindex: 21.29055555555555, humidex: 22.3, inDewpoint: 10.932958553958837, inHumidity: 48, inTemp: 22.5, maxSolarRad: 159.6840246961603, outHumidity: 27, outTemp: 22.3, pressure: 1017, rain: 0.0, rainRate: 0.0, usUnits: 17, UV: 0, windchill: 22.299999999999997, windDir: 216, windGust: 0.7777777783999998, windSpeed: 0.6944444449999999

I suspect you have missed a setting somewhere.  If you attach a copy of your weewx.conf file I'll compare it with mine (remove any passwords), but I don't think this is a ws6in1 driver problem

Regards

Bob

**Comment by sainio** [comment]
[weewx.conf.txt](https://github.com/BobAtchley/weewx-ws6in1/files/6231111/weewx.conf.txt)
Run the config again from the scratch, same result.

**Comment by BobAtchley** [comment]
I've compared my weewx.conf with yours.  Nothing really to report.  There are 2 things you might want to change but I don't think either are causing any problems:
1) in StdConvert section you have target_unit = US.  I have set this to METRICWX.  This parameter specifies how data is stored in the database - if you never intend to look at the database leave as US, but otherwise I would suggest changing (if you change this you need to delete the current database) [it could be that the output is what weewx is storing in the database]
2) in corrections just put a '#' in front of the foo = foo + 0.2

So this suggests it is a setting in the console that needs correcting, but looking at my manual this is mostly obvious and if you are seeing metric values on the console it must be correct.

Can you look at the weewx graphs that are put in public_html - it could be that these are actually correctly output in metric

**Comment by sainio** [comment]
I made the change and now it logs in metrics, thanks!  I asume, that the database was ok, based on the docs, it really should not make any difference, which DB units are used, but I like the logs better this way!

**Comment by BobAtchley** [comment]
Great.  I wish the US would join the rest of the world in using metric units.
